name: CI Checks

on: [pull_request, workflow_dispatch]

jobs:
  has-increased-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: henrikjoreteg/version-compare@main
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm ci
      - name: Run unit tests
        run: npm test
